### ISSUE TITLE
Leaking atoms.

### ISSUE THREAD

**Issue by vic** [grych/drab#1]
I'm reading drab's source, and just noticed two or three places were we have `String.to_atom` mostly on `Drab.do_handle_cast` to convert the event_name into a function name. Would it be better to have `String.to_existing_atom` as I guess *most* DOM events wont likely change, and there's just a handfull of the most commonly used ones. So if you are interested, I could provide a PR just to use `to_existing_atom` and have peace of mind. 

Thanks for drab again!

**Comment by grych** [comment]
Good point, thanks a lot!

About the event name, we shouldn't just specify the list, as user/library may create a new one. I am going to just keep it in String - as well as the other case, where I convert the button name to atom.

The third case is when browser sends us the event handler function and Drab launches this function with `apply/3`:

    apply(
        commander(socket), 
        String.to_atom(evt_fun), 
        [socket, dom_sender]
    )

This is easy - I just changed it to `to_existing_atom/1`. How can I be sure that this atom already exists? The handler function must exists and be compiled, and functions are represented by the atom in the AST tree :)

TODO: create an user-friendly message, when somebody misspell the handler function name. Now it raises with `** (ArgumentError) argument error` which may be quite a confusing.
