### ISSUE TITLE
map from form inputs, selects

### ISSUE THREAD

**Issue by benjamin79** [grych/drab#10]
Hi,

in your example it says

>  params: Map %{name|id => value} of all inputs, selects, etc which are in the alert box 

for modals.

I´m not sure if drag might to solve what i´m looking for, but at the moment i submit the forms in phoenix and get the params in the controller (new for example). I´d like to get rid of the page refresh and instead send the form to a commander function. I can´t query every input by id or class cause the form is dynamically generated.

Is this possible?

thanks

**Comment by grych** [comment]
Well, you can always query on, for example, all `<input>` in some `<form>`, and you'll get a list. Or even all inputs in the whole page:

    Drab.Query.select(socket, :val, from: "input")

But you'll get only the list of vals. I will think about replacing the list of `val()` with `name|id:val()` - maybe that's a good idea. This is what you want to archive?

**Comment by benjamin79** [comment]
I´m not sure what you mean. But i´d like to have exactly the same as in phoenix with params:
  `def create(conn, params) do`
On submitting a form i get a map in params with keys by the name. So for example if i have multiple input elements with  
 `name="user[question_answer][1][answer][]"` ..  `name="user[question_answer][2][answer][]" ...`
i get something like this in params["user"]:
```
%{"question_answer" => %{
    "0" => %{
      "question" => "Question_1"},
    "1" => %{"answer" => ["Answer_1"],
      "question" => "Question_2"},
    "2" => %{
      "question" => "Question_3"},
}}
```

**Comment by grych** [comment]
Drab works with completely different way. It works with the live page, moving all work you do normally on JavaScript side, to Elixir.

So in your case you need to imagine **how would you like to solve it on browser-side, with JS, jQuery and Ajax**. You probably collect your inputs with something like `$("input[name=question]")` and then send it as JSON with Ajax.

Drab does exactly the same, but collecting your data should be done in the event handler in the Commander, after you click the button. 

```
def button_clicket(socket, _dom_sender) do
  all_questions_list = socket |> select(:val, from: "input[name=question]")
  all_answers_list = socket |> select(:val, from: "input[name=answer]")
  ...
end
```

**Comment by benjamin79** [comment]
Thanks for your feedback.
