### ISSUE TITLE
How to have a Drab powered partial template shared across every page?

### ISSUE THREAD

**Issue by guidotripaldi** [grych/drab#102]
I would like to have a sort of "status bar" as the header of every page, where the content is updated by a shared Commander when somethings happens in other .drab pages. Something like:

_File `templates/layout/app.html.eex`_ :
```html
<html>
  <body>

      <header class="header">
          <%= render "_status_bar.html", Map.put(assigns, :my_status, MyApp.Status.get_current_status() ) %>
      </header>

      <main role="main">
          <%= render @view_module, @view_template, assigns %>
      </main>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <%= Drab.Client.run(@conn) %>
  </body>
</html>
```

_FIle `templates/layout/_status_bar.html.drab`_:
```html
<div>
   <%= inspect @my_status %>
</div
```

_FIle `status_commander.ex`_:
```elixir
defmodule MyApp.StatusCommander do
  use Drab.Commander

  onconnect :connected

  defhandler connected(socket) do
    status = MyApp.Status.get_current_status()
    update_status_bar(socket, status)
  end

  defhandler update_status(socket, sender) do
    status = peek(socket, :status)
    update_status_bar(socket, status)
  end

  def update_status_bar(socket, status) do
    poke(socket, status: status)
  end

end 
```

_File `another_page.html.drab`_:
```html
   <button type="button" drab='click:MyApp.StatusCommander.update_status()'>Update Status Bar</button>
```

but, as I understand, this is not possible because Drab needs a partial to be rendered inside a specific Controller hierarchy, as the status bar, being a partial rendered from the shared app template, do not have its own specific Controller hierarchy.

Which is the right way to achive this?

**Comment by grych** [comment]
To use `poke`/`peek` in the partial, you need to specify partial name and, in case it is a partial from the different view, a view name.

    defhandler update_status(socket, sender) do
      status = peek(socket, MyApp.StatusView, "_status_bar.html", :status)
      update_status_bar(socket, MyApp.StatusView, "_status_bar.html", status)
    end

This is because assigns are partial specific, for example you might have an assign with the same name in the different partials.

https://hexdocs.pm/drab/0.7.6/Drab.Live.html#module-partials

**Comment by guidotripaldi** [comment]
Oh, yeah, explicit view and partial name disambiguate the assigns. It was in the documentation, sorry
