### ISSUE TITLE
Custom Modal

### ISSUE THREAD

**Issue by guidotripaldi** [grych/drab#105]
I notice that if you want to render a custom template for a button when calling `Drab.Modal.alert/4` from an umbrella app, you have to configure the full application path, because Drab doesn't prefix `:templates_path` with the current application directory:

```elixir
# config/dev.exs
config :drab, 
  templates_path: "/my/app/full/path/priv/templates/drab"
```

so I've modify `lib/drab/config.ex` to read the app name from the configuration and add the right prefix to the template path:

```elixir
# config/dev.exs
config :drab, 
  app: :my_app_web,
  templates_path: "priv/templates/drab"
```

Furthermore, I've modified `Drab.Modal.alert/4` to support many different custom templates. Now you can pass the file name of the preferred custom template this way:

```elixir
alert(socket, "Title", "Shows this message with default OK button", template: "my_custom.modal.alert.html.eex")
```

Try to [take a look](https://github.com/guidotripaldi/drab/tree/custom-modal/lib/drab), then if you like I can PR the branch

**Comment by grych** [comment]
Closing this thread as you already introduced PR #106 :-)

**Comment by grych** [comment]
Could you please check the current master and let me know, if it solved your issue?

**Comment by guidotripaldi** [comment]
Yes, it fix it! :)

**Comment by grych** [comment]
Cool!
