### ISSUE TITLE
Multi-select form gets only one value

### ISSUE THREAD

**Issue by fmcgeough** [grych/drab#108]
Elixir 1.6.x
Phoenix 1.3
Drab: master from git

```
  <form drab="submit:updatetest">
    <div class="form-group">
      <select class="form-control" id="post_mortem_incident_causes" multiple="" name="post_mortem[incident_causes][]" placeholder="Incident Causes">
<option value="1">Process Gap</option>
<option value="2">Design Gap</option>
<option value="3">Configuration</option>
<option value="4">Result of Change</option>
<option value="5">Software Bug</option>
<option value="6">Infrastructure</option>
<option value="7">Human Error</option>
<option value="8">FCC Reportable</option>
<option value="9">3rd Party</option></select>
  </div>
  <button type="submit" >update mini</button>
</form>
```

If more than one item is selected the server code always gets just 1. The first one in the list selected.

%{"post_mortem" => %{"incident_causes" => ["1"]}}

**Comment by grych** [comment]
Could you please give master a try? Should be solved with the latest commit.

BTW if you put `name="post_mortem[incident_causes][]"`, you'll get a list of 1-element lists, it is better to have `name="post_mortem[incident_causes]"`

**Comment by fmcgeough** [comment]
Thank you. This works perfectly now. FYI, I believe I had that particular syntax because it was what Phoenix form multi_select generates.

**Comment by grych** [comment]
> 
> I believe I had that particular syntax because it was what Phoenix form multi_select generates.

I will have to check it, it would be good to mimic all Phoenix behaviour to be consistent with.
