### ISSUE TITLE
Mismatched title position in modal.alert.html.eex template header

### ISSUE THREAD

**Issue by guidotripaldi** [grych/drab#109]
Instead of

```
# priv/templates/drab/modal.alert.html.eex

<div id="_drab_modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog <%= class %>" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>

. . .

</div>

```

should be

```
# priv/templates/drab/modal.alert.html.eex

<div id="_drab_modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog <%= class %>" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h4 class="modal-title"><%= title %></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>

. . .

</div>

```

**Comment by grych** [comment]
Hmm, this way it does not look OK in my browser. Maybe it is a different bootstrap version? 

<img width="509" alt="modal" src="https://user-images.githubusercontent.com/101086/39051496-1d64af92-44a9-11e8-9ae9-10f8e4bd768d.png">

**Comment by guidotripaldi** [comment]
I'm using Boostrap 4, tested on a Mac
with all browsers (Firefox, Chrome, Safari) I see:

drab modal orig:
![drab modal orig](https://user-images.githubusercontent.com/12702951/39052514-87323dd8-44ac-11e8-9a8a-a39ad439a210.png)

drab modal modified:
![drab modal mod](https://user-images.githubusercontent.com/12702951/39052513-8704d406-44ac-11e8-96e6-33d420361206.png)

**Comment by grych** [comment]
Looks like incompatibility between BS3 and 4.

So there is no good solution for this. BTW Drab should not be dependent on any css or js library (except of phoenix socket), that's why we should do #96.

Please use your own template for now. I will leave it like it is (compatible with BS3).
