### ISSUE TITLE
Error when using custom events

### ISSUE THREAD

**Issue by Batou99** [grych/drab#123]
Example: trying Drab and using it with Bootstrap `eonasdan datetimepicker`. That component fires a `dp.change` event instead of a pure `change` event when date is changed. 

If we add on a .drab template:

```
 <%= text_input @f, :start_date, drab: "dp.change:start_date_changed", class: "form-control datepicker", "data-date-format": "YYYY-MM-DD" %>
```

The event `dp.change` is fired but it's not picked up by `Drab`

This is probably because now Drab defines client side events in a very naive way. Actually it is:

```
function update_event_handler(node, event, func) {
  // TODO: learn more about event listeners
  // node.removeEventListener(event, func)
  // node.addEventListener(event, func)
  node["on" + event] = func;
}
```

So the `node["on" + event] = func;` is only suited to standard events like `onchange`, `onclick` etc.

This is happening with elixir `1.6.1`, phoenix `1.3.0` and drab `0.7.7`

**Comment by grych** [comment]
Thanks for reporting!

**Comment by Batou99** [comment]
@grych I submitted a PR to fix it.

**Comment by grych** [comment]
Reopening, as it misbehaves in Firefox. Observe the first example from https://tg.pl/drab
