### ISSUE TITLE
Drab.Element.set_html/3

### ISSUE THREAD

**Issue by grych** [grych/drab#131]
Create `set_html/3` as a shortcut to `set_prop socket, "selector", innerHTML: html`

**Comment by guidotripaldi** [comment]
I can take care of this, so I can resume also the PR for cookies

**Comment by grych** [comment]
Cool, please assign yourself so noone else will do the same

**Comment by guidotripaldi** [comment]
I think I cannot self assign because I'm not either the maintainer or a collaborator of this repo

**Comment by grych** [comment]
I've made you a collaborator

**Comment by grych** [comment]
Absolutely, that's it.
PR please.
