### ISSUE TITLE
Updated data attribute not showing in dom_sender

### ISSUE THREAD

**Issue by benwalks** [grych/drab#14]
Hi Tomek,

First of all, thanks for creating Drab, I love the concept.

The issue I'm running into is a pretty simple use case where I'm attempting to favourite an item in the DOM, which updates a class from `is-unselected` to `is-selected` and also update a data attribute `data-favourited` from `false` to `true`.

The element that calls Drab is:

```
%svg(class="o-card-favourite #{selected(@listing)}" length="29px" version="1.1" viewbox="30 29" width="30px", xmlns="http://www.w3.org/2000/svg" "xmlns:xlink"="http://www.w3.org/1999/xlink" id="favourite-#{@listing.id}" drab-click='toggle_favourite' data-listing="#{@listing.id}" data-user="#{@user.id}" data-favourited="#{length(@listing.users) > 0}"}
```

And the associated commander is:

```
def toggle_favourite(socket, dom_sender) do
    user_id = dom_sender["data"]["user"]
    listing_id = dom_sender["data"]["listing"]
    favourited = dom_sender["data"]["favourited"]

    if (favourited) do
      unfavourite_listing(socket, dom_sender, user_id, listing_id)
    else
      favourite_listing(socket, dom_sender, user_id, listing_id)
    end
  end

  defp favourite_listing(socket, dom_sender, user_id, listing_id) do
    changeset = Favourite.changeset(%Favourite{}, %{user_id: user_id, listing_id: listing_id})
    case Repo.insert(changeset) do
      {:ok, _favourite} ->
        socket
        |> update(class: "is-unselected", set: "is-selected", on: this(dom_sender))
        |> update(attr: "data-favourited", set: true, on: this(dom_sender))
      {:error, changeset} ->
        IO.puts dom_sender
    end
  end

  defp unfavourite_listing(socket, dom_sender, user_id, listing_id) do
    favourite = Repo.get_by(Favourite, %{user_id: user_id, listing_id: listing_id})
    case Repo.delete(favourite) do
      {:ok, struct} ->
        socket
        |> update(class: "is-selected", set: "is-unselected", on: this(dom_sender))
        |> update(attr: "data-favourited", set: false, on: this(dom_sender))
      {:error, changeset} ->
        IO.puts dom_sender
    end
  end
```

Clicking the favourite icon once correctly updates the DOM according to the browser's DOM inspector (both the data attribute and the class are changed as they should), but clicking on the favourite icon once more (without a page reload) does not cause the `dom_sender` map argument to update the `data-favourited` property (it's value will be false, even when the DOM has been updated to true).  This is not the case upon refreshing the browser.  This occurs consistently whether the `data-favourited` has been set to true or false and is not being updated in the attached `dom_sender` argument, but is being updated in the DOM itself.

Any help is very much appreciated, please let me know if you need more information.

**Comment by grych** [comment]
Hi Ben,
thanks for the interesting issue, I learned something from this.
You should not directly set `data-xxx` attributes. Please use `update(:data)` instead:

    socket |> update(data: "favourited", set: true, on: this(dom_sender))

This is because jQuery's `data()` method does not update the attribute! It is well explained in the first answer of the following question:
http://stackoverflow.com/questions/7261619/jquery-data-vs-attr

Please notice me if it works for you.

I will update the documentation and I am thinking about generating a warning when anybody wants to update data via attribute or property.

**Comment by benwalks** [comment]
This works perfectly, thanks for the quick response @grych.  I've certainly learnt something new as well re: data attributes.
