### ISSUE TITLE
Individual options for enable/disable controls

### ISSUE THREAD

**Issue by guidotripaldi** [grych/drab#146]
If tag `drab="..."` is present, a control can't get disabled:

```eex
<button disabled id="my-button1" drab="click:do_something">Button 1</button> <!-- despite `disabled` attribute, button remains still enabled -->

<button disabled id="my-button2">Button 2</button> <!-- this instead works -->
```

neither trying to disable via `set_prop` works:

```elixir
# in Commander
def_handler disable_button(socket, _sender) do
   set_prop(socket, "#my-button1", disabled: true) # despite `disabled: true`, button remains still
   set_prop(socket, "#my-button2", disabled: true) # this instead works
end
```

**Comment by grych** [comment]
By default, Drab controls enable/disable behaviour. You may turn it off with options:

https://hexdocs.pm/drab/Drab.Config.html#module-configuration-options

**Comment by guidotripaldi** [comment]
thanks, but I cannot find a suitable option, can you suggest  which are the right one?

**Comment by grych** [comment]
`disable_controls_while_processing` and `disable_controls_when_disconnected ` - just turn it off

**Comment by guidotripaldi** [comment]
But they seems to control the behavior during request processing or when there isn't a connection, not when a control is just wait for some event

**Comment by grych** [comment]
Yes, but on page load (before connection) they disable all drab controls, and re-enable them when the connection establish.

**Comment by guidotripaldi** [comment]
I think that changing these options aren't a good solution, because they defaults are the right choice for the app-wide behavior of all controls. Instead it would be preferable to have the possibility to set someway the enabled/disabled state just for some controls.

**Comment by grych** [comment]
Agreed, let's do like this.

**Comment by guidotripaldi** [comment]
for example, instead of re-enable all controls when the connection establish, it should restore the previous setting (if a control was set as disabled, it will restored as enabled, and vice versa)

**Comment by grych** [comment]
I assume the issue is only for disconnect/connect, not for start/end of processing (as it can't be started only by enabled control).

I will do your way, with saving the enabled/disabled state of the button on disconnect. Details:
* on page load, drab.js saves the initial state of the control
* on disconnect, the state is saved again (as it may change in the meantime)
* on connect, the saved state is restored
