### ISSUE TITLE
how to render a template from the commander

### ISSUE THREAD

**Issue by mithereal** [grych/drab#15]
hello again, i need to render a template from the commander
ive read your code and it appears i should be able to use this in the commander

```
params = %{ beginaddress: beginaddress, endaddress: endaddress}
Drab.Template.render_template("customer_session.html.eex",  params  )
```

to render the file located in /priv/templates/drab/customer_session.html.eex
however i get an error no function clause matching in EEx.eval_file/3 but i am only passing 2 args is this correct use of this fun

also do you have an idea how i can make brunch copy my drab templates from /web/static/templates/drab to /priv/templates/drab

**Comment by somarasa** [comment]
you can use https://hexdocs.pm/phoenix/Phoenix.View.html#render_to_string/3 
Example: render_to_string(AppName.SharedView , "mtm_search_form.html",mtm_params: mtm_params)

**Comment by mithereal** [comment]
bindings must be a list

**Comment by mithereal** [comment]
after using a list binding i still get ehr error 
```
./priv/templates/drab/customer_session.html.eex:1: expected variable "assigns" to expand to an existing variable or be part of a match
beginaddress = "1111"
params = [ beginaddress: beginaddress ]
Drab.Template.render_template("customer_session.html.eex",  params  )

```
customer_session

`<input type='hidden' id='begin_address' value='<%= @beginaddress %>' />`

**Comment by grych** [comment]
Please never use Drab.Template, this is a private module for internal use only.

As @somarasa mentioned, use `Phoenix.View.render_to_string` instead. There is an example of how to do it, in the Drab Tutorial, https://tg.pl/drab#waiter.

Also I would not keep my templates in `priv/templates/drab`, as it is a private place for internal use (Drab keeps there all its templates, like javascripts or modal form html).

**Comment by mithereal** [comment]
ok thanks that clears up a lots of confusion for me!!
