### ISSUE TITLE
Update Select Values

### ISSUE THREAD

**Issue by iwada** [grych/drab#17]
Not a Bug/issue.  
Trying to update the values on a linked Select 
 This doesn't work.

    socket 
      |> update(:val, set: ["One","Two"], on: "#instance_deployment_data_center")
 
Please how best can i achieve this?

**Comment by grych** [comment]
It should work as expected, cycle between "One" and "Two" on this select.

Added an example on https://tg.pl/drab/docs#query (last example in section `update/2` and `update/3` to check. Works. Cycles between the values of the `select`

```html
    <select id="qu_11_select">
      <option value="One">One</option>
      <option value="Two">Two</option>
    </select>
    <button drab-click="qu_11_click" class="btn btn-primary">Clickme</button>

```

```elixir
  def qu_11_click(socket, _dom_sender) do
    socket |> update(:val, set: ["One", "Two"], on: "#qu_11_select")
  end
```

**Comment by grych** [comment]
Or maybe you want to rather change the `option` list than the value of `select`? In this case you need to modify the `html` of your `select`, like

```elixir
options = """
<option value=1>First</option>
<option value=2>Second</option>
"""

socket |> update(:html, set: options, on: "#qu_11_select")
```

**Comment by iwada** [comment]
@grych , Thank You. Was looking at the changing the `options`. Maybe that could be  added as an example at https://tg.pl/drab/docs ?
