### ISSUE TITLE
Add performance description for Drab.Live

### ISSUE THREAD

**Issue by safwanolaimat** [grych/drab#175]
Hello All
this first time i use drab 
i have basic example 
i have table and clock label
the first time you open the page the table will contain 10 rows 
the value of the clock from backend
everything working perfectly till now

when i rendered 1000 rows in the table the clock being too slow it take more than 3 seconds to render the clock again 

Thanks

**Comment by grych** [comment]
That would be easier if you put some code samples, please.

If you use Drab.Live, having the long html may be tricky as it must re-render it all the time you update. Please consider using the other technique to update the page, like Drab.Element. See https://elixirforum.com/t/drab-is-slow-in-production/17826/8

**Comment by guidotripaldi** [comment]
@grych 
maybe this question and the related elixiforum post could be a suggestion to add to the wiki documentation two new chapters, the first describing both by text and visually through some Sequence Diagrams, the Drab operations behind the scenes (compilation, rendering, handshaking, etc); the second chapter about the performances (how to keeps the performances good, errors to avoid, some benchmarks, ...). I think it could be useful as a reference for both newbie and seasoned  Drab developers, and to reduce the learning curve needed to master this package.
What do you think? I can help undertaking some parts.

**Comment by safwanolaimat** [comment]
@grych 
i am just new to drab so how to update assigns without reload all the page ?

**Comment by grych** [comment]
Yes, please! I believe it is documented in the Engine part, how Drab does re-render of the page, but it is always good to have it described.

I will also update documentation of Drab.Live and Drab.Core with the performance part.

**Comment by grych** [comment]
> i am just new to drab so how to update assigns without reload all the page ?

This is not about reload the page. Drab does not reload the page (in the browser), it updates the changed part. But to do it, in needs to re-render the page on the server side. If the page is big, it takes time.

Please read the manual in https://tg.pl/drab and documentation to find out how it works.

**Comment by guidotripaldi** [comment]
> Yes, please!

ok! I'll submit some drafts next days

**Comment by safwanolaimat** [comment]
@grych  its too small but 
but every poke to browser all the assigns reloaded

**Comment by grych** [comment]
Please update with some code snippets. I can't guess what's the issue..

**Comment by grych** [comment]
> every time clock update the uploads assign also rerendered

Because you can see the "LOG" in the console? This is correct, because every time you update anything the page is re-rendered in the backend. It does not mean that the page in the browser is being update at that part.

**Comment by safwanolaimat** [comment]
@grych 
okay 
how to update assign without update the whole page ?

**Comment by grych** [comment]
There is no way. After you change the assign, the whole page must be re-rendered.

See my first comment:
If you use Drab.Live, having the long html may be tricky as it must re-render it all the time you update. Please consider using the other technique to update the page, like Drab.Element. See https://elixirforum.com/t/drab-is-slow-in-production/17826/8

**Comment by guidotripaldi** [comment]
@safwanolaimat 
[here](https://github.com/guidotripaldi/drab_speed) you will find the source of a simple app that allows you to compare the Drab performances of different page designs and Drab techniques under different load conditions, and choose which can be better to use in your specific case. Coming soon also the online version.
