### ISSUE TITLE
Drab resets scroll position when updating DOM

### ISSUE THREAD

**Issue by kelostrada** [grych/drab#176]
Whenever I change any variables in Commander and I have some nested scroll which is in different then default position I will have DOM reloaded hence `scrollTop` will reset to 0. Is there any workaround to keep the scroll position?

**Comment by grych** [comment]
I had the same issue creating naive chat, please take a look https://tg.pl/drab#chat_example. Simply, I just sent the JS:

    broadcast_js socket, "document.querySelector('#chat').scrollTop = document.querySelector('#chat').scrollHeight"
