### ISSUE TITLE
Important information about Tomasz (I am his colleague)

### ISSUE THREAD

**Issue by norus** [grych/drab#183]
Guys,

Tomasz didn't ask me this, but I thought I'd let you all know that he suffered from a stroke last weekend.

It may take some time before he is back at full throttle.

Get well soon, buddy!

**Comment by GoNZooo** [comment]
Wow, that's awful. Please, @grych, take the time to rest and recuperate and come back even stronger! We all appreciate the hard work you do, but be mindful to take some hours off everything and don't spend too much of yourself. I'm routing for you!

**Comment by guidotripaldi** [comment]
Thank you Norus, please keep us informed about his health conditions!

**Comment by grych** [comment]
I am already in :) will take some time to recover
