### ISSUE TITLE
Compatibility with Phoenix 1.3

### ISSUE THREAD

**Issue by JanStevens** [grych/drab#19]
Trying to get phoenix 1.3-rc2 to work with latest drap

```

=INFO REPORT==== 12-Jun-2017::16:33:40 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application drab: exited in: DrabTestApp.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function DrabTestApp.start/2 is undefined (module DrabTestApp is not available)
            DrabTestApp.start(:normal, [])
            (kernel) application_master.erl:273: :application_master.start_it_old/4

```

Seems to me your mix.exs file contains `[mod: {DrabTestApp}]` when it shouldn't

**Comment by grych** [comment]
`DrabTestApp` is the application used for tests (and development), and it is not included in the hex package.

However, Phoenix 1.3 is not supported yet. I am going to restrict it it to `~> 1.2.0` for now (next release, 0.5.0). Phoenix 1.3 will be supported in version 0.6.0

**Comment by JanStevens** [comment]
Hoo thats a shame, I made it work by adding a fake `DrabTestApp` in my application and so far everything works. The broadcast doesn't seem to work (2 tabs open, broadcast on same page, no change in the other tab).

Any idea when v1.3 support will land? Really looking forward this for some small projects

**Comment by grych** [comment]
That'a a good workaround, everything else should be compatible with 1.3. I planned to test Drab with 1.3 after the stable version arrives, being busy with the other parts of the library.

Could you please elaborate about the broadcast? A code sample that I may replicate the issue, please.

**Comment by JanStevens** [comment]
Sure

```elixir
# commanders/page_commander
defmodule LocalScanning.Web.PageCommander do
  use Drab.Commander

  def toggle(socket, dom_sender) do
   # This just toggles the state from offline to online for example
   current = LocalScanning.Settings.Storage.toggle!
   socket
    |> update!(:text, set: "Working #{current}", on: this(dom_sender))
    |> update_class(dom_sender, {:mode, current})
  end

  defp update_class(socket, dom_sender, {:mode, :online}) do
    socket |> update!(class: "btn-danger", set: "btn-success", on: this(dom_sender))
  end

  defp update_class(socket, dom_sender, {:mode, :offline}) do
   socket |> update!(class: "btn-success", set: "btn-danger", on: this(dom_sender))
  end
end
```

```elixir
<a class='btn btn-<%= if @mode == :online, do: :success, else: :danger %>'
   drab-event="click" drab-handler="toggle">Working <%= @mode %></a>
```

```elixir
defmodule DrabTestApp do
  def start(_, _) do
    {:ok, self()}
  end
end
```

**Comment by grych** [comment]
@JanStevens,
thanks!
All looks OK. It must be an issue with Phoenix 1.3 compatibility. I am leaving this issue as a bug, I am going to deal with this just after I finish 0.5.0

**Comment by grych** [comment]
@JanStevens,
the issue is with `this(dom_sender)`. It returns the sender node - so the button in the specific browser, just where you click it. This is why it does not propagate to the others.

You should give the button an `id` and use `#id` selector, or use `this!(dom_sender)` instead. Notice that `this!/1` also requires an `id` to be set.

https://hexdocs.pm/drab/Drab.Query.html#this!/1

**Comment by JanStevens** [comment]
Haa thanks, I ended up using a class and just do a `on: '.mode-button'`, the ID did work but only for one element on the page ( I have that button in multiple places), now the broadcast also works.

Thanks!
