### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by SampsonCrowley** [grych/drab#194]
Is there a listing of supported browsers for drab?

**Comment by OvermindDL1** [comment]
Nothing 'official', but as long as the web browser supports websocket or at least polling fallback (I.E. if it supports standard phoenix channels) then it will work.  I've used it on IE10 at work (though thankfully everything is upgraded to IE11 at least now) though.  Is there something specific, a feature or so, that you are looking for?

**Comment by SampsonCrowley** [comment]
no there's just literally no mention of browser support anywhere, or required polyfills, etc..

can't add something like this into production without knowing what markets it can be used in

**Comment by OvermindDL1** [comment]
Heh, well it has the same requirements as phoenix channels, beyond that at it's most basic it just runs passed over javascript so at that point it depend son what you send over it.  Drab is just a simple javascript tunnel to talk across with some useful tools built on top.  :-)

But yeah, that should be documented in the readme, one moment...

**Comment by OvermindDL1** [comment]
How's that?  :-)

**Comment by SampsonCrowley** [comment]
Perfect. even just clarifying that it should work on any browser that supports Phoenix sockets should be enough for people to get an idea of if they can drop it in

**Comment by OvermindDL1** [comment]
Awesome, thanks for bringing this up!  Documented clarification is always useful.  :-)
