### ISSUE TITLE
mix drab.gen.commander Name error on version 0.4.1

### ISSUE THREAD

**Issue by boilercoding** [grych/drab#21]
```
** (RuntimeError) could not find drab.gen.commander.ex.eex in any of the sources
    lib/mix/phoenix.ex:24: anonymous fn/5 in Mix.Phoenix.copy_from/5
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/mix/phoenix.ex:19: Mix.Phoenix.copy_from/5
    lib/mix/tasks/drab.gen.commander.ex:24: Mix.Tasks.Drab.Gen.Commander.run/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

**Comment by grych** [comment]
What is the Phoenix version?

**Comment by boilercoding** [comment]
Phoenix version 1.2.4. The file ```priv/templates/drab/drab.gen.commander.ex.eex```  is not present in version 0.4.1.

In drab version 0.3.1 in ```lib/mix/tasks/drab.gen.commander.ex``` you have in the run function:
```elixir
Mix.Phoenix.copy_from paths(), "priv/templates/", "", binding, [
      {:eex, "drab.gen.commander.ex.eex", "web/commanders/#{path}_commander.ex"}
]
```
And the file drab.gen.commander.ex.eex is present at ```priv/templates```

In drab version 0.4.1 in ```lib/mix/tasks/drab.gen.commander.ex``` you change in the run function:
```elixir
Mix.Phoenix.copy_from paths(), "priv/templates/drab/", "", binding, [
      {:eex, "drab.gen.commander.ex.eex", "web/commanders/#{path}_commander.ex"}
]
```
But the file drab.gen.commander.ex.eex is not present at ```priv/templates/drab```

What I did was to download version 0.3.1 and copy the drab.gen.commander.ex.eex file to my dependency. I would love to help if you want, are PR welcomed?

**Comment by grych** [comment]
Hi @boilercoding,
thanks! Actually, this file disapeared! I reverted it back so it will appear again in 0.5.0.

Any help appreciated! About PR, I am only posting updates to elixirforum.com, announcing new versions, roadmap etc. - which is obviously not enough.
