### ISSUE TITLE
Replace all Mix references

### ISSUE THREAD

**Issue by smpallen99** [grych/drab#26]
The following will now work https://github.com/grych/drab/blob/master/lib/drab.ex#L281 for a release. To fix this, replace with:

```
        "rebel.handler_error.#{Atom.to_string(env())}.js",
```

and add this to the module.

```
  @env Mix.env
  def env, do: @env
```

**Comment by OvermindDL1** [comment]
Yeah `Mix` does not exist at deployment time.  You could always `unquote` a mix call into position, but don't call it straight.

**Comment by grych** [comment]
Actually, I am going to get rid of all the features based on Mix.env. It does not make sense in the project which is used as a dependency, as deps are always compiled as prod.
