### ISSUE TITLE
Does not work on Ios !

### ISSUE THREAD

**Issue by pyladune** [grych/drab#3]
it seems there is just no reaction on IOS devices (iphone, ipad)

Any idea why ?

**Comment by grych** [comment]
Hi @pyladune, could you please give me the iOS version (of both devices, iphone and iphad).

I assume we are speaking about Demo Page, https://tg.pl/drab, are we?

**Comment by pyladune** [comment]
ios 9.2.1

Yes, only demo page tested

**Comment by grych** [comment]
Thanks! I've found the issue, I've used some EM6 specific constructs in the client JS library. Changed it to traditional JS.
Patch will be included in 0.2.3, coming very soon.

**Comment by grych** [comment]
Fixed in 0.2.3, thanks for reporting that!

**Comment by pyladune** [comment]
impressively fast reaction !!

As a complement feedback this works fine in ios 9.

Just the broadcast example seems not to work fully. it yorks fine locally but nothing is broadcasted either in ou out

**Comment by grych** [comment]
True. Broadcast does not work in and out iOS (regardless of the version, the same is on iOS10). Reopening the issue.

**Comment by grych** [comment]
The issue with broadcast is not connected to iOS version; broadcast does not work with multiple phoenix servers behind the load balancer. As a workaround, I shut one phoenix down and leave the only one working.

Closing this issue and open a new one.
