### ISSUE TITLE
Warnings on every single request

### ISSUE THREAD

**Issue by OvermindDL1** [grych/drab#30]
Getting these warnings on every single request:
```elixir
[warn] :max_age was not set on Phoenix.Token.verify/4. A max_age is recommended otherwise tokens are forever valid. Please set it to the amount of seconds the token is valid, such as 86400 (1 day)
```
In significant amounts.  A max_age should be specified to something to prevent reply attacks later.  :-)

**Comment by grych** [comment]
What's the Phoenix version?

**Comment by OvermindDL1** [comment]
Master, the warning was added in this commit:  https://github.com/phoenixframework/phoenix/commit/16d340d23a7faba95d55ea543f623bf56f8cdf8a#diff-dfff98abf14a9bea2145de1b0fd0b5d1

Plus there should always be a max_age anyway even in older versions (preferably short enough to encompass the request and no longer), else the token is replayable.
