### ISSUE TITLE
Can not run tests

### ISSUE THREAD

**Issue by vfsoraki** [grych/drab#33]
While trying to run tests, I encounter the following error:

> ** (ExUnit.DuplicateDescribeError) describe "Drab.Query delete" is already defined in DrabTestApp.QueryTest
>     test/integration/query_test.exs:404: (module)
>     (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
>     (elixir) lib/code.ex:376: Code.require_file/2
>     (elixir) lib/kernel/parallel_require.ex:59: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5

Although I'm on Elixir 1.5, this does not seem to be related to #31 .

Any idea what I might be doing wrong?

**Comment by grych** [comment]
Thanks!
