### ISSUE TITLE
Controller Assign doesn't update if inserted with render_to_string

### ISSUE THREAD

**Issue by axedbits** [grych/drab#38]
Hey, i'm trying to update an assign, for example @imgname, used within Phoenix.View.render_to_string("img.html", imgname: imgname), inserted with insert_html after a successful upload.

I then have a form to change the @imgname, with a button to Confirm, but it only updates the assign used in the index.html.

Is this expected behavior or should it update?

I've also experienced the issue #34.

Thanks for developing drab! All the best.

**Comment by grych** [comment]
This is a similar issue as #34. Will be resolved in the next release.

Thanks for the report!

**Comment by grych** [comment]
Fixed in v0.5.4
