### ISSUE TITLE
Broadcast does not work correctly on the multiple-server configuration

### ISSUE THREAD

**Issue by grych** [grych/drab#4]
Broadcast send the messages only to the clients connected to the same server.

**Comment by grych** [comment]
Although it is a Phoenix configuration issue, I will keep it open as it would be good to mention about it in documentation/guides.

**Comment by OvermindDL1** [comment]
It should broadcast to all channels fine if using the channel broadcast, if it does not then maybe phoenix bug as the pubsub is distributed.  o.O

**Comment by grych** [comment]
You are right, it should broadcast. I just never configured Demo Page server to work in a cluster. Now it is working on just one server. It is only matter of configuration, as described here: https://dockyard.com/blog/2016/01/28/running-elixir-and-phoenix-projects-on-a-cluster-of-nodes

I left this issue opened to remember to do it some day.

**Comment by grych** [comment]
Clustered exisiting Drab Demo server, all works as expected in 2-node configuration
