### ISSUE TITLE
checkbox value not reported correctly in sender["form"]

### ISSUE THREAD

**Issue by nico-amsterdam** [grych/drab#41]
Phoenix:  1.2, Elixir: 1.4.5,  Drab: 0.5.3

I had a problem with checkboxes. In sender.params and sender["forms"] I did get the checkbox value, as if it was checked. 
HTML:
```HTML
<input name="mycheckbox" type="hidden"   value="false">
<input name="mycheckbox" type="checkbox" value="true" >
```
I always got mycheckbox="true"

To fix it:
in drab.events.js, function default_payload(sender, event)
change: 
  `if (input.type == 'radio') `
into:
  `if (input.type == 'radio' || input.type = 'checkbox')`

**Comment by grych** [comment]
Fixed in v0.5.4
