### ISSUE TITLE
[Drab.Live] Should assign as an <input> value be changed when user change it?

### ISSUE THREAD

**Issue by grych** [grych/drab#43]
```html
<input value="<%= @assign %>">
```

Currently, you may `poke` and `peek` the assign, but when the user changes the value, `peek` shows the original one. This is by design, and mentioned in docs.

Proposition: update every time user changes the value. It would be way more intuitive.

**Comment by bopjesvla** [comment]
The `value` attribute should stay a one-way binding. There are many cases where you don't want the server-side value to change until the user commits the changes (by pressing a save button, for example). Also, the proposed behavior is ambiguous: does the value update oninput or onchange?

Two-way bindings are useful, though, and you could steal the syntax from MVVM libraries like [Vue](https://vuejs.org/v2/guide/forms.html#Modifiers):

```html
<input drab-v="<%= @assign %>">
<input drab-v.lazy.number="<%= @assign %>">
```

**Comment by grych** [comment]
Convinced.
