### ISSUE TITLE
Upcase and Downcase examples fail and reload page in Firefox on MacOS

### ISSUE THREAD

**Issue by auxbuss** [grych/drab#45]
MacOS 10.12.6
Firefox 55.0.2

On the [demo page](https://tg.pl/drab?text_to_uppercase=uppercase+me), when clicking the `Upcase` and `Downcase` buttons, a page reload is initiated (and the text is not changed). All other demos appear to be working.

These actions work in Safari.

**Comment by grych** [comment]
Thx for reporting!

I did reproduce this. Looks like Firefox submits the form with the `<button>` instead of just lauching the event. This is different behaviour than Safari or Chrome.
