### ISSUE TITLE
Slow build times 

### ISSUE THREAD

**Issue by benjamin79** [grych/drab#54]
Hi, i´ve tried drab in the dev instance of our app. It´s a rather big one with many (10) nested views. Rebuild times go from 1-2 s to 20 -30s.  I can´t publish that app to show you. But perhaps you have an idea how i can debug this.

**Comment by grych** [comment]
EEx engine is not optimized yet. In this stage the only optimization I made is to the runtime, sacrificed the compile time.

Should be better with the new engine v0.6.0.

BTW I understand the most of the build time it is spending with compiling templates (showing `14:13:51.840 [info]  Compiling Drab partial:...`?

**Comment by benjamin79** [comment]
I will look what the output is when i´m back.  But i think so.

**Comment by grych** [comment]
Could you please re-check with the current master? Compile time should be way shorter.
