### ISSUE TITLE
if assigns not working with drab

### ISSUE THREAD

**Issue by benjamin79** [grych/drab#55]
In some templates i have 

`<%= if assigns[:something] do %> `

As soon as drab is active by changing the extension to .drab the if results to true even it the variable doesn´t exist. When i remove .drab everything works. There doesn´t need to be a commander file either. Just adding .drab leads to this.  I can show you an example app when i´m back (mid -end october) but i thought i let you know as soon as possible. Perhaps you have an idea.

thanks for the great tool.

**Comment by grych** [comment]
I've tried to reproduce this issue by simple:

```
<%= if assigns[:nonexisting] do %>
  true
<% else %>
  false
<% end %>
```

And I have the expected result. Could you please share the code?

**Comment by benjamin79** [comment]
Yes, i will. As soon as i´m back. Sorry it will take a while.

**Comment by benjamin79** [comment]
Can´t reproduce it at the moment.
