### ISSUE TITLE
Support for `slim` templates

### ISSUE THREAD

**Issue by Bharat311** [grych/drab#56]
Hi, First of all great work. I am currently using slim templates in my app using the `phoenix-slime` package but i am getting some strange error when working with drab. (Drab.Live.Poke)

Are the slim templates not yet supported ? I even tried mixing in an `eex` in between the slim templates but still no luck.

Could you please let me know, how i could make it work in my app.

Thanks

**Comment by grych** [comment]
Hi @Bharat311 
`Drab.Live` only supports HTML templates. I am not planning to integrate other templating systems in the near future (even if it would be much easier to implement :)

But you should be able to use modules like `Drab.Element` or `Drab.Query`, they are not using special eex engine.

**Comment by OvermindDL1** [comment]
I 'think' the main slime package has the ability to output strings in standard eex format.  You could feed those into Drab Live's renderer then.
