### ISSUE TITLE
Add key_code value as part of dom_sender map

### ISSUE THREAD

**Issue by taorg** [grych/drab#6]
Hello we are using awesome develop with a new project
This is not a bug, but a feature.
We think it could be quite useful for keyboard events to add the key_code within the dom_sender
sometimes, you don't want to process every key pressed.
For instance, want to load an autocomplete pop-up with values for a web-service, but no with every key pressed, because it takes too much CPU.
We don't see how could it be done now.

Thanx

**Comment by grych** [comment]
By default, events send some information back to the server, as described in docs here - https://hexdocs.pm/drab/Drab.Commander.html#content - so you can have the value, text, html etc of the sender DOM object. Maybe it is a good idea to add the event object here, so you could read its properties. I'll think about it.

The simple example is here https://tg.pl/drab#broadcast - but it launch the event on every key press. From the performance perspective, it would be nice to have some kind of "throttle" event, which is launched on the JS side when user stop pressing the keys with some delay, like 0.5 second. I will add it to the TODO

**Comment by taorg** [comment]
Thank you  @grych

**Comment by grych** [comment]
Added in v0.2.6

* added event object with specified properties to the dom_sender
* added `debounce` function as an option to the event handler
