### ISSUE TITLE
Drab on selected actions in controller

### ISSUE THREAD

**Issue by jung-hunsoo** [grych/drab#65]
I'm first to use drab on my new webapp. Currently drab is used in new/edit form, via `before_hander`.

So I wanted to `Drab` only some actions like `use Drab.Controller, only: [:new, :edit]` but no luck.

Is there any way (or plan to) apply selected drabbing?

**Comment by jung-hunsoo** [comment]
In addition, how about allowing private function for `onload`, `onconnect`, and `ondisconnect`?

It's unable to call private function for these callbacks.

**Comment by grych** [comment]
`use Drab.Controller` is only for indicate that this controller has the corresponding commander. Commander for Drab is what controller is for phoenix.

Please read the docs for [controller](https://hexdocs.pm/drab/Drab.Controller.html#content), [commander](https://hexdocs.pm/drab/Drab.Commander.html#content) and [readme](https://hexdocs.pm/drab/readme.html#usage).

About the callbacks handlers, they must be public functions.
