### ISSUE TITLE
BadMapError in Drab.Live.assigns

### ISSUE THREAD

**Issue by mradke** [grych/drab#69]
## Env

phoenix version: 1.3.0
drab version: 0.6
elixir version: 1.6

No jquery / bootstrap setup is used.

## Steps to recreate

* Follow the steps in the setup section
* Create a new controller / router / ... method and template for `testpage`
* Give the template an assign `drab_example`
* Add callback to the PageCommander, like:

```
  onload(:page_loaded)

  def page_loaded(socket) do
    poke(socket, drab_example: "42 is the answer")
  end
```

### Expected behaviour

The text on `testpage.html.drab` should change on load to the given string.

### Observed behaviour

Drab throws an error, stating:

```
[error] Drab Handler failed with the following exception:
** (BadMapError) expected a map, got: nil
    (stdlib) :maps.find(nil, nil)
    (drab) lib/drab/live.ex:421: Drab.Live.assigns/3
    (drab) lib/drab/live.ex:298: Drab.Live.do_poke/5
    (drab) lib/drab.ex:205: anonymous fn/3 in Drab.handle_callback/3
```

#### Notes

* This only happens, when called from the commander. If I use IEx instead (as per the examples) and call `socket |> poke(drab_example: "some string")` the assign changes as expected
* When debugging this I noticed that `do_poke` is  calling `assigns/3` with a `nil` for `partial` and `partial_name`. Normally this should not be possible when looking at the code, since the `index/1` function work correctly if called from IEx...

Thanks for this library. I really like the idea 👍

**Comment by grych** [comment]
Thanks for reporting! True, I've never tested poking the assign in page load callback.

**Comment by mradke** [comment]
Let me know if I can be of further assistence. Just `poke` me 😉
