### ISSUE TITLE
Multiple event handlers in html element

### ISSUE THREAD

**Issue by IrwinBridge** [grych/drab#73]
For example, if you want to do like this:
<input drab-focus="input_focus" drab-blur="input_blur">

But it doesn't work.

When i try to put it like this:
<input  drab-event="focus" drab-handler="input_focus" drab-event="blur" drab-handler="input_blur">

Only the first one works and the second ignores.

**Comment by GoNZooo** [comment]
It seems that the HTML you posted wasn't picked up on the actual GitHub page (at least it doesn't render here). I'll repost it for you:

> For example, if you want to do like this:
>
> `<input drab-focus="input_focus" drab-blur="input_blur">`
>
> But it doesn't work.
>
> When i try to put it like this:
>
> `<input  drab-event="focus" drab-handler="input_focus" drab-event="blur" drab-handler="input_blur">`
>
> Only the first one works and the second ignores.

**Comment by grych** [comment]
HTML does not allow multiple attributes with the same name, so it will be done like:

```html
<input drab-event-1="focus" drab-handler-1="input_focus" drab-event-2="blur" drab-handler-2="input_blur">
```

**Comment by grych** [comment]
Also, I am going to extend the shortcut events list (drab-click, drab-change), now it is only

```js
["click", "change", "keyup", "keydown"]
```

**Comment by IrwinBridge** [comment]
Or you can make event list accessible for changing.

**Comment by grych** [comment]
```elixir
config :drab, :events_shorthands, ["click", "keyup", "blur"]
```

Please keep this list short, it affects client script performance

**Comment by grych** [comment]
Multiple events for the DOM object will also work with the shorthand form:

    <input drab-focus="input_focus" drab-blur="input_blur">

One handler for the event.
