### ISSUE TITLE
umbrella usage

### ISSUE THREAD

**Issue by jschoch** [grych/drab#79]
I'm working on an umbrella app where the main router checks the hostname and then routes along to the other umbrella apps endpoints.  I am getting the following error and wanted to ask if your umbrella tests had the main app serving the sockets.

`failed: Error during WebSocket handshake: Unexpected response code: 403
connect @ phoenix.js:869
(anonymous) @ phoenix.js:813
disconnect @ phoenix.js:848
(anonymous) @ phoenix.js:812
(anonymous) @ phoenix.js:1474`

my setup has drab running "server: false" in HostDomainApp

browser_client -> RtrApp -> HostDomainApp

I'm not seeing the console messages about the sockets either.  Just wondering if this has been tested and is expected to work or if the main app also has to be running drab.

**Comment by grych** [comment]
Honestly, I've never tested Drab in such configuration. Could you please share some code, how could I reproduce the issue? Or even better, if you could create a simple project with the config I could play with, it would be appreciated.

**Comment by jschoch** [comment]
I was able to get this working but not the way I'd have liked.  The example can be found here:

https://github.com/jschoch/drab_umbrella_example

Big question now is "can you have more than one drab behind a proxy umbrella app?"

Please take a look and let me know if i'm doing anything silly or insecure.  Hope to close once you've reviewed.

**Comment by grych** [comment]
I can't see any issues. If your router routes the websocket, this is all what Drab wants!

> Big question now is "can you have more than one drab behind a proxy umbrella app?"

I can't see the reason why not. You just need to [setup the different websocket path](https://hexdocs.pm/drab/Drab.Config.html#content) for drab2, and route it similarly as to DrabExample.
Try!

> I'm also wondering why phoenix seems to ignore this:

Overwritten by DrabExample? The default socket path for Drab is /socket
