### ISSUE TITLE
drab-click events not triggered with set_prop outerHTML 

### ISSUE THREAD

**Issue by bougueil** [grych/drab#80]
I wish to add dynamically buttons like
```
set_prop socket, selector, outerHTML: "<button drab='click:button_clicked'>clickme</button>"
```
however `button_clicked` is not called.

**Comment by grych** [comment]
Good find, thanks!
It is a bug, `outerHTML` is not on the list of updates, which should re-read drab's events. Until it is solved, please use `innerHTML` or the parent element.
