### ISSUE TITLE
Drab.get_priv returns an empty map on onload

### ISSUE THREAD

**Issue by bougueil** [grych/drab#86]
Drab.get_priv returns an empty map on a page_loaded callback (onload)

this is reproducible with a Raspberry Pi Model B Rev 2 (a slow device)
phoenix is started as a **systemd** service 
https://elixirforum.com/t/elixir-apps-as-systemd-services-info-wiki/2400
MIX_ENV=dev
Drab 0.7.1

some log:
```
13:19:30.457 [warn] page_loaded socket: pid #PID<0.459.0>
13:19:30.463 [warn] page_loaded socket: get_priv %{}
13:19:30.514 [error] Drab Handler failed with the following exception:
** (ArgumentError) Drab is unable to find a partial main.
Please check the path or specify the View.

    (drab) lib/drab/live.ex:540: Drab.Live.assign_data_for_partial/3
    (drab) lib/drab/live.ex:313: Drab.Live.do_poke/5
    (ffplay_ex) lib/ffplay_ex_web/commanders/page_commander.ex:26: FfplayExWeb.PageCommander.page_loaded/1
    (drab) lib/drab.ex:233: anonymous fn/3 in Drab.handle_callback/3
```

**Comment by grych** [comment]
Hey, thanks for reporting! Is it happening on vanilla drab installation on raspberry?

**Comment by bougueil** [comment]
yes, Raspbian stretch lite
https://www.raspberrypi.org/downloads/raspbian/

however outside systemd, phoenix/drab is working well on raspbian.
on my desktop systemd / phoenix / drab is also working.




On Mon, Mar 5, 2018 at 5:21 PM, Tomek Gryszkiewicz <notifications@github.com

**Comment by bougueil** [comment]
drab-example seems to have the same issue if you update it's mix drab
version to 0.7.1

**Comment by bougueil** [comment]
Hmm, maybe a firefox (linux 58.0.2 64-bit) bug ?
not reproduced with chromium

**Comment by grych** [comment]
No errors on js console on client side? Does the same Firefox open other drab pages (tg.pl/drab) without issue?

**Comment by bougueil** [comment]
firefox was configured with a network proxy hence the issue 
closing this
