### ISSUE TITLE
Pass options to Phoenix.Channel

### ISSUE THREAD

**Issue by grych** [grych/drab#89]
To control websocket logging

**Comment by makeitrein** [comment]
Ahoy, is `config :drab, :phoenix_channel_options, [log_handle_in: false]` supposed to disable the following message? If so, I probably did something wrong in my config! If not, would be great if I could suppress this message, it's getting a bit excessive...

``` Started Drab for __drab:same_path:/, handling events in FicdbWeb.FanficCommander
    You may debug Drab functions in IEx by copy/paste the following:
import Drab.{Element, Live, Query, Core}
socket = Drab.get_socket(pid("0.749.0"))

    Examples:
socket |> set_style("body", backgroundColor: "red")
socket |> poke(text: "This assign has been drabbed!")
socket |> select(:htmls, from: "h4")
socket |> exec_js("alert('hello from IEx!')")
```

Many thx for making Drab!

**Comment by grych** [comment]
This is a Drab message, and it shows only when started with iex in developer mode. There is no way to suppress it yet, but I would accept the PR with configuration option to hide this message.
