### ISSUE TITLE
Hitting `enter` on a form where the submit button is a drab event reloads the page

### ISSUE THREAD

**Issue by stevepm** [grych/drab#90]
I expect that when I hit enter OR when I click the submit button on a form, the drab event will be called, but the drab event is only called when I hit submit, and the page is reloaded when I press `enter`

**Comment by grych** [comment]
Hi @stevepm, thanks for reporting.
Could you please share your form? I can't reproduce the issue in my environment, this:

```html
<form drab="submit:update_mini">
  <input>
  <button type="submit" >update mini</button>
</form>
```

works perfectly on both click and hit Enter.

**Comment by stevepm** [comment]
I'll test it out later tonight, but I was using the example in the introduction section here https://tg.pl/drab, where the `drab` modifier was only added to the button. I'll try adding it to the form instead.

**Comment by grych** [comment]
Please share the exact form, and the browser version you use.

**Comment by grych** [comment]
Hi @stevepm, a humble reminder.
I can't reproduce the issue.
