### ISSUE TITLE
"Jason" not found in production

### ISSUE THREAD

**Issue by guidotripaldi** [grych/drab#94]
(Maybe related with issues [#25](https://github.com/grych/drab/issues/25), [#26](https://github.com/grych/drab/issues/26))

When in production,  the 'Jason' dependency cannot be found. 

A workaround is to add  {:jason, "~> 1.0"} to the app mix.exs file.

**Comment by grych** [comment]
Hi @guidotripaldi, thanks for reporting!
This is a bug, I forgot to add it to `applications`. Will be fixed in the next release.

For a workaround, you may also add it to applications in the release.
