### ISSUE TITLE
Modal dialog isn't showed calling Drab.Modal.alert/4

### ISSUE THREAD

**Issue by guidotripaldi** [grych/drab#95]
I cannot be able to show a simple modal dialog using the Drab.Modal module. My set is:

Elixir: 1.6.4
Phoenix: 1.3
Drab: 0.7.3

File _PageCommander.ex_:
```elixir
defmodule FrontendWeb.PageCommander do
  use Drab.Commander

  def test_modal(socket, sender) do
    Drab.Modal.alert(socket, "This is a test")
  end
end
```

File _PageController.ex_:
```elixir
defmodule FrontendWeb.PageController do
  use Drab.Controller
  ...
end
```

File _index.htm.drab_:
```html
 <button type="button"  drab="click: test_modal">Test Drab Modal</button>
```

Clicking the button nothing appears on the page, but the button goes disabled. Looking at the page source, the code for bootstrap modal is correctly being inserted after the button is clicked, though the modal doesn't show up:

```html
<div id="_drab_modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog " role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title">--TITOLO--</h4>
      </div>
      <div class="modal-body">
        <form>
          <p>BODY</p>
          <input id="__drab_modal_hidden_input" type="submit" style="position: absolute; left: -9999px; width: 1px; height: 1px;">
        </form>
      </div>
      <div class="modal-footer">
        <button id="_drab_modal_button_ok" name="ok" type="submit" class="btn btn-primary drab-modal-button" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>
```

If I try to display a bootstrap modal in the standard way, it shows up correctly. I'm using Bootstrap 4, installed trough npm. Others drab elements coded in the same app works well, so I think it is maybe a bug or a version conflict.

---
Let me say that Drab is a outstanding package, terribly useful, with simple and elegant api. I think it should become a standard element of  the elixir/phoenix ecosystem, as ecto and other packages are!
This way it would have a perfect integration with Phoenix, following better its evolution.
I don't know how, but I think that Drab users should press Jose/Chris to think seriously about this.

**Comment by grych** [comment]
For `Modal`, you need to have jquery installed and exposed as global ([see README, installation section](https://hexdocs.pm/drab/readme.html#installation)). Also, this module is not loaded by default:

    use Drab.Commander, modules: [Drab.Query, Drab.Modal]

This is because each module has a corresponding javascript part, which need to be loaded. By default, `Drab.Live` and `Drab.Element` are loaded, leaving the rest - including `Drab.Modal` optional.

https://hexdocs.pm/drab/Drab.html#module-modules

I will leave this issue opened, as it should be better explained in the docs (in every optional module doc).

**Comment by guidotripaldi** [comment]
Oh yes, I've missed that part of documentation, thank you! Adding
```elixir
use Drab.Commander, modules: [Drab.Live, Drab.Element, Drab.Query, Drab.Modal]
```
to my Commander resolves my issue.

Maybe can be useful to add a reminder on every Module documentation that it is necessary to load the module, giving the above sample

**Comment by grych** [comment]
> Let me say that Drab is a outstanding package, terribly useful, with simple and elegant api. I think it should become a standard element of the elixir/phoenix ecosystem, as ecto and other packages are!
This way it would have a perfect integration with Phoenix, following better its evolution.
I don't know how, but I think that Drab users should press Jose/Chris to think seriously about this.

Ecto is not a part of Phoenix! And I think also Drab should not be, not everyone needs it. But it would be nice to have something like `--with-drab` in the `phx.new` task :) I will propose after 1.0.
