### ISSUE TITLE
v. 0.7.3 broken with 414: url too long

### ISSUE THREAD

**Issue by guidotripaldi** [grych/drab#97]
It seems that v. 0.7.3 broke the possibility to use `@changeset` as the parameter for `form_for`.  Given this sample code (that works well with 0.7.1)
```eex
<!--File index.html.drab -->
  <button type="button" drab="click:drab_test">DRAB TEST</button>
 
  <%= form_for @changeset, "/my/path",  fn f -> %>
    <%= input f, :test_field %>
    <%= submit "Submit" %>
  <% end %>
```
```elixir
# File test_commander.ex
  defmodule MyApp.TestCommander do
    use Drab.Commander
    def drab_test(socket, sender) do
      IO.inspect sender, label: "drab_test"
    end
  end
```

the Commander function isn't called at all when the button is clicked, and the browser console show many WebSocket errors like these when the page is loaded:

> *WebSocket connection to 'ws://localhost:4000/socket/websocket?__drab_return=SFMyNTY.g3QAAAACZAAEZGF0YWwAAAAFaAJkAAxfX2NvbnRyb2xsZXJkACRFbGl4aXIuRnJvbnRlbmRXZWIuQWNjb3VudENvbnRyb2xsZXJoAmQAC19fY29tbWFuZGVyZAAjRWxpeGlyLkZyb250ZW5kV2ViLkFjY291bnRDb21tYW5kZXJoAmQABl9fdmlld2QAHkVsaXhpci5Gcm9udGVuZFdlYi5BY2NvdW50Vmlld2gCZAAIX19hY3Rpb25kAARlZGl0aAJkAAlfX2Fzc2lnbnNqamQABnNpZ25lZG4GAG98J59iAQ.3tZAACbsnr3ThtDXrGGKdEk9YlFA8LAH5QBEX45Ults&__priv%5Bassigns%5D%5Bge3daojrga2dmmrq%5D%5Bchangeset%5D=QTEyOEdDTQ.pcBDLYjF5vwOQRHLgc3usgeLO37Yo4H9X78qB...a8laiwyu0w7hPZUFS_7GlIuSe1WMul3fCesBeomaKVd_9G6RHOopzPU9_ncbH5gluD0_oDGBVMMLSjALasN7e8w9K7BGddSeBX2U_cOfb1mbjKjh017b-Dt1rsWAxJgLCI6JUnlsvMq5Dk8uuJjkwr_sLWNqXWK98Z0nYaLauZNEHtfJvvdqXbwniKKDRAae18zpE79BJ_5jkH1Zqs4LCZlVnmGqV9sJ7F-fEJgMtYe6P4OGtMtfdMBJG9jJw3Fg_ECKZxDgLUG0PxncsocG74lFtgiqPFbBD4HyBMsubuNepG3FgwV84mw6xz2j7scS2xWevJuUB4AhhbnNK-3zSmrg16KK7uoW6Qf0Tq_F3hozvE6Kyi0Fdb59VaJTGMSROwha_LxJ7-ewfBq6tk4T2N9cCKYApJmy1wcvsDHU9SY-1zOiVMC9pzqiH.NndL55U2To5TFBOq50-jJA&&__priv%5Bindex%5D=ge3daojrga2dmmrq&vsn=2.0.0' failed: Unexpected response code: 414*
> 
> *WebSocket network error: The operation couldn’t be completed. Connection reset by peer*

Instead, if we use`@conn` instead of `@changeset` 
```eex
<!--File test.html.drab -->
  <button type="button" drab="click:drab_test">DRAB TEST</button>
 
  <%= form_for @conn, "/my/path",  fn f -> %>
    <%= input f, :test_field %>
    <%= submit "Submit" %>
  <% end %>
```
drabs work well as usual without any WebSocket error also using 0.7.3.

**Comment by grych** [comment]
Hi @guidotripaldi, thanks for reporting!

Is there any log on the server side? Should be something about `Drab.Socket.verify`.

**Comment by guidotripaldi** [comment]
No I'm sorry, I cannot see any log from Drab one the server side

**Comment by grych** [comment]
Yes, I missed the http response: 414 (url too long).
This is a bug, and must be solved quickly, as it will cause errors on every page with big assigns.

**Comment by guidotripaldi** [comment]
I haven't yet studied your code so I cannot give help in fixing errors, but I'm at your disposal for debugging.

**Comment by grych** [comment]
Thanks a lot! I already know what is wrong.
When the page connects, client sends all assigns to the server (to have in cached on the server side, so there is no latency in peek, and less latency in poke). In 0.7.2 I've changed the way it is doing it, moving it to the connect token, which is passed as url parameter.
This caused an error, when there is too many assigns or they contain too many data.

**Comment by guidotripaldi** [comment]
v 0.7.4 installed, all seems ok now! I check it extensively and will report any error
