### ISSUE TITLE
How to store/retrieve a cookie from Drab?

### ISSUE THREAD

**Issue by guidotripaldi** [grych/drab#99]
I would like to use Drab to update and retrieve cookies in a Commander `eventhandler`. Given that there is no way to update the Session from Drab as Session is read-only, I wondering if there is some way to do that.

For example,
```html
	<button type="button"  drab="click:set_cookie(42)">Set cookie</button>
	<button type="button"  drab="click:use_cookie()">Use cookie</button>
```

```elixir
defmodule MyCommander do
  use Drab.Commander

  defhandler set_cookie(socket, sender, cookie_value) do
    cookie_name = "foo"
    # how to store my cookie_value into my cookie named "foo"?
  end

  defhandler use_cookie(socket, _sender) do
    cookie_value =  # how to retrieve it?
    do_something_with_cookie(cookie_value)
  end

end
```

Maybe cookies are accessible trough Drab.Query, but I cannot find a way to replicate `$.cookie("foo", 42);`

If there isn't a plain way, maybe could be useful to extend Drab with a specific set of functions for manipulating cookies.

**Comment by grych** [comment]
There is no helper function(s) to get/set cookies. Roughly, you may just use `document.cookie` in the browser:

    exec_js socket, "document.cookie"

and for setting:

    exec_js socket, "document.cookie='val1=aaa;cookie2=bbb'

**TODO**: it would be nice to have a getter/setter in Drab, working with Elixir data structures. It should be in Drab.Browser module and the API should be something like:

    iex> cookie1 = Drab.Browser.cookie(socket, "session") ### getter
    %Drab.Browser.Cookie{value: "...", expires: #DateTime<2018-04-09 12:39:50.435883Z>, path: "/"}

    iex> Drab.Browser.cookie(socket, "new_cookie", cookie1) ### setter
    %Drab.Browser.Cookie{value: "...", expires: #DateTime<2018-04-09 12:39:50.435883Z>, path: "/"}

    iex> Drab.Browser.cookies(socket") ### all cookies
    [%Drab.Browser.Cookie{...}, %Drab.Browser.Cookie{...}]

**Comment by guidotripaldi** [comment]
Oh, yes, it was simple! :)

**Comment by guidotripaldi** [comment]
Maybe could be something like that? 

```elixir
  ## setter
  #    Parameters:
  #      socket:  the Drab socket
  #      name: the cookie name
  #      value: the cookie value, can be an Elixir data structure
  #   options:
  #     max-age: 
  #            > 0    - sets the cookie max-age, in seconds.
  #            == 0   - sets a session cookie
  #            < 0    - delete the cookie
  #     path: the cookie path, default "/" 
  #  Usage:
  #    cookie(socket, "Items", [%{id: 001, name: "foo"}, %{id: 002, name: "bar"}], max_age: 3*24*60*60)
  #
  def cookie(socket, name, value, options\\[]) do
    max_age = Keyword.get(options, :max_age, 0)
    path = Keyword.get(options, :path, "/")
    exec_js(socket, "document.cookie='#{name}=#{Poison.encode!(value)}; expires=#{cookie_expires(max_age)} path=#{path}'")
  end

  defp cookie_expires(max_age) do
      cond  do
        max_age > 0 ->
          Timex.local
          |> Timex.add(%Timex.Duration{megaseconds: 0, seconds: max_age, microseconds: 0})
          |> Timex.format!("{RFC1123}")
        max_age == 0 ->
          ""
        max_age < 0 ->
          "Thu, 01 Jan 1970 00:00:00 GMT"
      end
  end

  ## getter
  #    Parameters:
  #      socket:  the Drab socket
  #      name: the cookie name
  #   Usage:
  #     items = cookie(socket, "Items")
  #     -->  [%{id: 001, name: "foo"}, %{id: 002, name: "bar"}]
  def cookie(socket, name) do
    case exec_js socket, "document.cookie" do
      {:ok, cookies} ->
        extract_cookie(cookies, name)
      _ -> ""
    end
  end

  defp extract_cookie(cookies, name) do
    cookie = 
      cookies
      |> String.split(";")
      |> Enum.filter(fn cookie -> String.starts_with?(cookie, "#{name}=") end)
      |> hd

    case Regex.run(~r/Cart=(.*)/, cookie) do
      [_, value] -> Poison.decode!(value)
      _ -> "" 
    end
  end
```

If you like, I can submit a PR for a new Drab.Browser.Cookie module

**Comment by grych** [comment]
This is a good start for the PR, thanks a million! 
* I like the API, that one I proposed in my first comment is an overkill (no need a struct, and getter doesn't have to know about path or max age)
* there is a fundamental issue: you can set only one cookie! All the other will be overwritten with `document.cookie=`. You should parse the cookie string and change only the appropriate part. I also suggest getter for all cookies 
* I am not sure about `Timex.local` - shouldn't it be a client local time, not the server? See `Drab.Browser.now/1`. By the other hand, "normal" cookie setting sets it by the server time, I suppose.
* please use `Drab.Core.encode_js` and `decode_js`  instead of Poison, for consistency (and we are using Jason with Drab)
* there should be two versions of each function, normal and bang one; bangs throws exceptions. See existing functions in `Drab.Browser`

**Comment by guidotripaldi** [comment]
Thank you for the hints. 
 - Yes, we have to set and retrieve all the cookies not just the named one (mine was just a quick solution to start with).
 - Yes, it is better to set the expiration with the browser time I think.
 - Ok, I'll change Poison with  Drab.Core.*_js
 - OK for bang versions.

Which is the right position/filename/name of the new module? Something like `lib/cookie.ex` and `defmodule Drab.Browser.Cookie` ?

**Comment by grych** [comment]
I would put it into the Drab.Browser, which already contains the similar helper functions.

**Comment by guidotripaldi** [comment]
I'm working on the new cookie functions. I had to change the previous names because of conflicts between clauses and defaults, now we have `get_cookie`, `set_cookie` and `delete_cookie`, and I create a new utils.ex module file with some helpers (i.e. `encode_param`, `decode_param`, ..).
Is is ok for you?

**Comment by grych** [comment]
I would do `cookie`, `cookies`, and `set_cookie` (without get_). About the new module - go for it! We may move more helpers from the existing modules there, would be easier to maintain and test.

**Comment by grych** [comment]
Looks good!

I saw you want to do encryption for cookies, this is cool. There are functions for this in Drab.Live.Crypto, you may use it. I will move them to Utils later.

For tests, all the functions interacting with modules must be tested with integration test with browser. I am using Hound and Chromedriver for this. You may want to extend `test/integration/browser_text.exs` or create your own.

**Comment by guidotripaldi** [comment]
I'm late on this. Hope to resume to develop this feature in a few days.

**Comment by grych** [comment]
No worries, you are helping a lot with all the bug you've found!
